apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: abbphonebook
  labels:
    app: abbphonebook
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abbphonebook
  template:
    metadata:
      labels:
        app: abbphonebook
        env: demo
    spec:
      containers:
      - name: abbphonebook
        image: 127.0.0.1:5000/abbphonebook
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: app-config
          mountPath: /app/config
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: backend-url
            path: .env
