kind: Service
apiVersion: v1
metadata:
  name: web-service
  namespace: abbphonebook
spec:
  selector:
    app: abbphonebook
    env: demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
